### ISSUE TITLE
minor Alert size/spacing Inconsistencies 

### ISSUE THREAD

**Issue by EHackettTriCore** [rackerlabs/helix-ui#255]
I noticed that the `hxDismiss` button has a different spacing than the `hxIcon` and `hxContent` in the alert element.

![alert-dimention-variations](https://user-images.githubusercontent.com/16137890/41604106-6e77586c-73ac-11e8-9667-b9a2eda22534.gif)

The `hxDismiss` becomes 48px/48px but the `hxIcon` ends up being 16px/20px with a 16px padding. The `hxContent` ends up having 16px padding top/bottom.

I think the solution would be to update the `hxDismiss` with the same dimensions as the icon/content.

**Comment by CITguy** [comment]
The `<hx-icon>` element will rarely be a 1:1 dimension, because it is an inline element that needs to comply with `line-height` values in order to align properly with surrounding content. However, the SVG image that is injected, will always be 1x1 em to match font size (which complies with `line-height` values).

The `hxDismiss` button requires different CSS in order to position the "X" 1rem from the top and right sides of the alert boundary _at all times_. If we were to use the same CSS styles on the `hxDismiss`, the `<button>` height would grow with the alert height, vertically aligning the "X" (because of user-agent styling of the `<button>` element), which is against spec.

<img width="493" alt="screen shot 2018-06-19 at 9 48 01 am" src="https://user-images.githubusercontent.com/545605/41605909-136ecf44-73a8-11e8-8eac-3adfdcae99ac.png">

<img width="489" alt="screen shot 2018-06-19 at 11 10 11 am" src="https://user-images.githubusercontent.com/545605/41609866-5f348a00-73b1-11e8-9600-d224b12839f4.png">


<img width="492" alt="screen shot 2018-06-19 at 9 43 08 am" src="https://user-images.githubusercontent.com/545605/41604743-961e2014-73a5-11e8-8cf4-3bf3feec08d6.png">


<img width="630" alt="screen shot 2018-06-19 at 9 43 17 am" src="https://user-images.githubusercontent.com/545605/41604742-960dacfc-73a5-11e8-95dd-453cf32b9644.png">

**Comment by CITguy** [comment]
Fixed in #311 and available since v0.13.0
