### ISSUE TITLE
Hx-File-Tiles fail to interpret title characters properly

### ISSUE THREAD

**Issue by jonkruse00** [rackerlabs/helix-ui#322]
## Describe the Bug
Implementing the new hx-file-tile and realized that the names of the files aren't being displayed properly. 

## Steps to Reproduce

1. Upload files with a variety of characters. 

## Expected behavior
To display names properly. 

## Screenshots
![screen shot 2018-08-27 at 9 46 14 am](https://user-images.githubusercontent.com/5339195/44666559-49c0b500-a9de-11e8-8944-be7c7c8ed885.png)

## Environment
Please complete the following information:

 - Device: desktop
 - OS: iOs
 - Browser: Chrome
 - Version: 48
 - Helix-ui version: 0.12.1

**Comment by jonkruse00** [comment]
```
  <div className="hxRow"> 
    <div className="hxCol hxSpan-12-xs hxSpan-6-sm hxSpan-4-lg">
      <HxFileTile
        data-tooltip={uuid}
        href={url}
        icon={icon}
        name={filename}
      />
      <hx-tooltip id={uuid} position="top" aria-hidden="true">
        {filename}
      </hx-tooltip>
    </div>
  </div>
```

[HxFileTile](https://github.rackspace.com/SDP/ConsolidatedTicketingUI/blob/master/src/components/shared/HxFileTile.tsx) is a basic wrapper for `hx-file-tile`

**Comment by CITguy** [comment]
What is the raw HTML that is produced? I've got a feeling that React may be the culprit with `name={filename}`.

**Comment by CITguy** [comment]
Ah, the problem seems to only exist when the `name` value is over 28 characters (needing truncation)

_28 characters (no truncation)_
<img width="426" alt="screen shot 2018-08-27 at 12 09 03 pm" src="https://user-images.githubusercontent.com/545605/44673769-0d974f80-a9f2-11e8-808a-de3afe81b68a.png">


_29 characters (truncation applied)_
<img width="431" alt="screen shot 2018-08-27 at 12 09 14 pm" src="https://user-images.githubusercontent.com/545605/44673777-1425c700-a9f2-11e8-907b-6211a73f4488.png">

**Comment by CITguy** [comment]
SURF-1356 created to capture work

**Comment by 100stacks** [comment]
Working on this now.

Preliminary testing shows this line may be the issue: https://github.com/rackerlabs/helix-ui/blob/master/src/helix-ui/elements/HXFileTileElement.js#L322

**Comment by 100stacks** [comment]
Bug fix submitted with PR https://github.com/rackerlabs/helix-ui/pull/331
