### ISSUE TITLE
When popover is opened by via attribute it does not update its position

### ISSUE THREAD

**Issue by nicko-winner** [rackerlabs/helix-ui#410]
## Describe the Bug
When popover is opened by via `open` it does not update its position on scroll.
![2018-12-11_19-50-31](https://user-images.githubusercontent.com/35456401/49839677-1d0e8e80-fd7e-11e8-9ba8-4bb7d34b716a.png)

## Steps to Reproduce
1. Go to: https://codepen.io/nicko-winner/pen/YdXemK
2. scroll up and down the page, you will see popover is fixed and does not update its position on scroll events.

## Expected behavior
The popover updates position on scroll to stay positioned next to the element launching the popover or `relative-to` element. 

## Environment
 - Laptop
 - OS: OSX
 - Browser: chrome
 - Version: Helix 15.rc.2

**Comment by CITguy** [comment]
Good catch!

`window` and `document` event listeners aren't attached if a positionable component is open before attaching to the DOM. This is because the `Revealable.$onConnect` runs before `Positionable.$onConnect`, emitting the `open` event before `Positionable` has a chance to add an event listener.

**Comment by CITguy** [comment]
@nicko-winner: please verify if the latest `v0.15.0-rc.3` release has corrected this issue.

**Comment by nicko-winner** [comment]
Nice fix!
