### ISSUE TITLE
Review .hxBtn display: inline-flex;

### ISSUE THREAD

**Issue by EHackettTriCore** [rackerlabs/helix-ui#426]
## Describe the Bug
In BareMetal we're using helix buttons with `Hx-Icon` inside of them. It appears that the style `display: inline-flex` which is assigned to the default '.hxBtn' ignores inline spacing between word and the icons. 

What is `display: inline-flex` intended to do vs `display: inline-block` etc? Removing it doesn't appear to effect the design examples.

## Steps to Reproduce
Create a `.hxBtn` element with an `Hx-Icon` inside of it. You'll notice that the icon touches the word vs respecting any text space you add between it and the word.

2. Click on '...'
3. Scroll down to '...'
4. ...
5. Dogs and cats living together!

## Expected behavior
I expect that if there is a blank space between the a `word` and the `hx-icon` that it will be visually shown.

## Screenshots
![example](https://user-images.githubusercontent.com/16137890/51140813-7e120200-1815-11e9-94a0-fe17b425a324.gif)

## Environment
Please complete the following information:

 - Device: Desktop Mac
 - OS: IOS 10.13.6
 - Browser: Chrome
 - Version: 71.0.3578.98

**Comment by CITguy** [comment]
As per [v0.14.0 release notes](https://github.com/rackerlabs/helix-ui/releases/tag/v0.14.0)...

> Text nodes within buttons _must be wrapped_ in a `<span>` if there are any non-text siblings

This is to address shortcomings with JSX compiling to inequivalent markup. Please see https://rackerlabs.github.io/helix-ui/guides/react-compatibility/ for more information.

**Comment by EHackettTriCore** [comment]
Hmmm i'm still confused what `display: inline-flex;` helps with. Was it added for the file uploader?

In my example I have a hard coded blank space between the text and the icon so `Actions`_`icon`.

<img width="454" alt="screen shot 2019-01-15 at 4 56 15 pm" src="https://user-images.githubusercontent.com/16137890/51212441-7f5f2f80-18e6-11e9-9ea3-dfc3e6ca9af7.png">
<img width="253" alt="screen shot 2019-01-15 at 4 55 31 pm" src="https://user-images.githubusercontent.com/16137890/51212446-80905c80-18e6-11e9-92f0-bb55fe0f48eb.png">
<img width="206" alt="screen shot 2019-01-15 at 4 55 35 pm" src="https://user-images.githubusercontent.com/16137890/51212450-825a2000-18e6-11e9-85f2-4e146f88e02f.png">

It appears JSX is respecting the space output in the DOM however the `display: inline-flex;` strips the space out. If `display: inline-flex;`  is changed back to `display: inline-block;` then it solves the button issue.

**Comment by CITguy** [comment]
## Inline Block Problems

Using `display: inline-block;` introduces the following issues:
* It affects layout of elements outside of the button, which ripples through styling of other components.
* Natural white space in markup is still rendered by the browser, resulting in unwanted white space rendered on screen.

## Limitations and Support
The issue is that we have to write CSS that supports various scenarios involving an unknown arrangement of a variable number of child nodes.

1. Text Only
2. Icon Only
3. Text + Trailing Icon
4. Leading Icon + Text
5. Leading Icon + Text + Trailing Icon
6. Text + Icon + Icon + ...
7 Icon + Icon + ... + Text
8. \* + \* + \* ...
9. etc.

You can try out the various test scenarios for yourself at https://codepen.io/CITguy/pen/LMorpm.

The only way to apply consistent spacing for all these scenarios is to use `display: inline-flex;` (removes the naturally rendered whitespace from markup) along with a CSS generic sibling combinator selector as follows:

```less
.hxBtn {
  display: inline-flex;

  .hxBtn > * + * {
    margin-left: 0.5rem;
  }
}}
```

**Comment by CITguy** [comment]
Also, JSX preserves white space between similar node types (text + text, element + element), but removes them between dissimilar node types (text + element).
