### ISSUE TITLE
Flashing Header Styles

### ISSUE THREAD

**Issue by EHackettTriCore** [rackerlabs/helix-ui#90]
Ok so it was bugging me and I was curious about web components and shadow DOM so I wanted to a bit of learning on the topic. And see if I could solve the blipping navigation and header on the reveal component.

If you disable the shadow DOM cloning you'll notice there is a discrepancy between the initial component styles and the one after the shadow DOM is cloned and it's css is applied.

![jitter](https://user-images.githubusercontent.com/16137890/32970978-37eff4de-cbb9-11e7-8e8e-1882678ff368.jpg)

I added those styles into `reveal.less`

```css
hx-reveal header {
  font-family: "Roboto", sans-serif;
  letter-spacing: normal;
}
```

This applies the style to the initial DOM text before it's regenerated during the js life cycle.

I'm wondering if there needs to be some kind of base font applied to all `hx-...` components. Anyway I hope that helps.

**Comment by CITguy** [comment]
This was fixed in #88. 

The issue was our lack of understanding around how the `<slot>` element behaves and its involvement in CSS style inheritance.  CSS style inheritance is based on the composed DOM tree, not the written DOM tree. What this means is that style inheritance may dip into the shadow dom (depending on the shadow dom markup) before it resolves in the light dom.
